In [19]:
import numpy as np


In [20]:
R = np.array([[5,3,0,1],[4,0,0,1],[1,1,0,5],[1,0,0,4],[0,1,5,4]])
print(R)

[[5 3 0 1]
 [4 0 0 1]
 [1 1 0 5]
 [1 0 0 4]
 [0 1 5 4]]


In [21]:
def martix_factorization(R, P, Q, K, steps = 10000, alpha = 0.0002, beta = 0.02):
    Q = Q.T
    for step in range(steps):
        for i in range(len(R)):
            for j in range(len(R[i])):
                if R[i][j] >0 :
                    eij = R[i][j] - np.dot(P[i,:],Q[:,j])#eij = Rij - sum(pij,qji)
                    for k in range(K):
                        P[i][k] = P[i][k]+alpha*(2*eij*Q[k][j] - beta*P[j][k])
                        Q[k][j] = Q[k][j]+alpha*(2*eij*P[i][k] - beta*Q[k][j])
                
            
    return P, Q.T


In [22]:
K = 2
N = len(R)
M = len(R[0])
P = np.random.rand(N,K)
Q = np.random.rand(M,K)

P_esti,Q_esti = martix_factorization(R,P,Q,K)
print(P_esti,'\n')
print(Q_esti)

[[0.3161648  2.4621725 ]
 [0.34001136 1.95940696]
 [2.16698781 0.39861229]
 [1.72766565 0.39432947]
 [1.72500376 0.66119926]] 

[[0.10574601 2.01198397]
 [0.19753951 1.18083661]
 [2.10164858 2.00636596]
 [2.27764227 0.11319411]]


In [24]:
R_esti = np.dot(P_esti,Q_esti.T)
print(R_esti)

[[4.98728477 2.96987846 5.6044864  0.99881375]
 [3.97825025 2.38090515 4.64587183 0.99621759]
 [1.03115184 0.8987617  5.35400899 4.9807436 ]
 [0.97607831 0.8069209  4.42211528 3.97964008]
 [1.51273457 1.12152469 4.95195939 4.00378534]]
